#!/bin/bash

#Install Script
#David Rhoads
#November 15, 2019
echo "This script installs all necessary components of my linux system. Note: it was written on PopOS 19.10 in November 2019, but should work on any Ubuntu bases system"



#Configure Flatpaks
#sudo add-apt-repository ppa:alexlarsson/flatpak &&
sudo apt update &&
sudo apt install flatpak
#Install Snap
sudo apt install snapd &&
sudo apt install gnome-software-plugin-flatpak &&
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo &&


#Install gphotos-sync
sudo snap install gphotos-sync
#Install Powershell
sudo snap install powershell --classic &&

#Install Visual Studio Code
sudo snap install code --classic &&

#Install git
sudo apt install git &&

#Download Plexamp AppImage
#wget https://plexamp.plex.tv/plexamp.plex.tv/plexamp-1.1.0-x86_64.AppImage &&
#Make it Executable
#chmod +x plexamp-1.1.0-x86_64.AppImage &&

#Install Shortwave
flatpak install flathub de.haeckerfelix.Shortwave

#Install Riot
snap install riot-web &&

#Install Planner
flatpak install flathub com.github.alainm23.planner &&

#Install Feeds
flatpak install flathub org.gabmus.gfeeds

#Install Gnome Podcasts
flatpak install org.gnome.Podcasts

#Install Geary
flatpak install org.gnome.Geary

#Install Lollypop
flatpak install org.gnome.Lollypop
#Install Syncthing
	# Add the release PGP keys:
	curl -s https://syncthing.	net/release-key.txt | sudo apt-key add - &&
	# Add the "stable" channel to your APT sources:
	echo "deb https://apt.syncthing.net/ syncthing stable" | sudo tee /etc/apt/sources.list.d/syncthing.list &&
	# Update and install syncthing:
	sudo apt-get update &&
	sudo apt-get install syncthing &&

#Install Gnome Tweaks
sudo apt-get install chrome-gnome-shell &&
sudo apt install gnome-tweaks &&
#Install Emby
wget https://github.com/MediaBrowser/Emby.Releases/releases/download/4.2.1.0/emby-server-deb_4.2.1.0_amd64.deb &&
sudo dpkg -i emby-server-deb_4.2.1.0_amd64.deb &&

#Install Plex
snap install plexmediaserver &&

#Install Joplin
wget -O - https://raw.githubusercontent.com/laurent22/joplin/master/Joplin_install_and_update.sh | bash

#Install KeepassXC
sudo add-apt-repository ppa:phoerious/keepassxc &&
sudo apt update &&
sudo apt install keepassxc &&

#Install Darktable
sudo apt install darktable &&

#Install Krita
sudo apt install krita &&

#Install Syncthing
sudo apt install syncthing-gtk &&

#Install neofetch
sudo apt install neofetch &&

#Install htop
sudo apt install htop &&

#Install Brave
sudo apt install apt-transport-https curl

curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add -

echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list

sudo apt update &&

sudo apt install brave-browser &&

#Install Ubuntu Studio Installer
sudo apt install ubuntustudio-installer &&

#Install MS Fonts
sudo apt install -y ttf-mscorefonts-installer &&

#Install Spotify
curl -sS https://download.spotify.com/debian/pubkey.gpg | sudo apt-key add - &&
echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list
sudo apt-get update && sudo apt-get install -y spotify-client &&

#Install Lutris
sudo add-apt-repository ppa:lutris-team/lutris &&
sudo apt update &&
sudo apt install lutris &&

#Install Steam
flatpak install flathub com.valvesoftware.Steam &&

#Install vlc
sudo apt install vlc &&

#Install youtube-dl
sudo snap install youtube-dl &&

#Uncomment below to install Zorin OS theming
#echo "Installing Zorin OS theming, you will need to install the following gnome shell extensions:
#User Themes, Tray Icons, Dash to Panel, and Arc Menu. Press [enter] to continue"
#read varname
#sudo apt install gettext libgettextpo-dev gnome-shell-extensions gnome-tweak-tool gnome-menus gir1.2-gmenu-3.0 &&
#git clone https://github.com/ZorinOS/zorin-desktop-themes.git &&
#git clone https://github.com/ZorinOS/zorin-icon-themes.git &&
#sudo cp -r zorin-desktop-themes/Z* /usr/share/themes &&
#sudo cp -r zorin-icon-themes/Z* /usr/share/icons &&



#Update all Packages
sudo apt update &&

#Upgrade all packages
sudo apt upgrade
