#!/bin/bash

#Install Script
#David Rhoads
#November 15, 2019
echo "This script installs all necessary components of my linux system. Note: it was written on PopOS 19.10 in November 2019, but should work on any Ubuntu bases system"



#Configure Flatpaks
#sudo add-apt-repository ppa:alexlarsson/flatpak &&
sudo apt update &&
sudo apt install flatpak
#Install Snap
sudo apt install snapd &&
#sudo apt install gnome-software-plugin-flatpak &&
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo &&

#Install git
sudo apt install git &&


#Install Syncthing
	# Add the release PGP keys:
	curl -s https://syncthing.	net/release-key.txt | sudo apt-key add - &&
	# Add the "stable" channel to your APT sources:
	echo "deb https://apt.syncthing.net/ syncthing stable" | sudo tee /etc/apt/sources.list.d/syncthing.list &&
	# Update and install syncthing:
	sudo apt-get update &&
	sudo apt-get install syncthing &&

#Install Gnome Tweaks
sudo apt-get install chrome-gnome-shell &&
sudo apt install gnome-tweaks &&
#Install Emby
wget https://github.com/MediaBrowser/Emby.Releases/releases/download/4.2.1.0/emby-server-deb_4.2.1.0_amd64.deb &&
sudo dpkg -i emby-server-deb_4.2.1.0_amd64.deb &&

#Install Plex
snap install plexmediaserver &&

#Install Joplin
wget -O - https://raw.githubusercontent.com/laurent22/joplin/master/Joplin_install_and_update.sh | bash &&

#Install neofetch
sudo apt install neofetch &&

#Install Brave
sudo apt install apt-transport-https curl

curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add -

echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list

sudo apt update &&

sudo apt install brave-browser &&

#Install Ubuntu Studio Installer
sudo apt install ubuntustudio-installer &&

#Install MS Fonts
sudo apt install -y ttf-mscorefonts-installer &&

#Install Lutris
sudo add-apt-repository ppa:lutris-team/lutris &&
sudo apt update &&
sudo apt install lutris &&

#Uncomment below to install Zorin OS theming
#echo "Installing Zorin OS theming, you will need to install the following gnome shell extensions:
#User Themes, Tray Icons, Dash to Panel, and Arc Menu. Press [enter] to continue"
#read varname
#sudo apt install gettext libgettextpo-dev gnome-shell-extensions gnome-tweak-tool gnome-menus gir1.2-gmenu-3.0 &&
#git clone https://github.com/ZorinOS/zorin-desktop-themes.git &&
#git clone https://github.com/ZorinOS/zorin-icon-themes.git &&
#sudo cp -r zorin-desktop-themes/Z* /usr/share/themes &&
#sudo cp -r zorin-icon-themes/Z* /usr/share/icons &&



#Update all Packages
sudo apt update &&

#Upgrade all packages
sudo apt upgrade
